添加简单的 302 文件重定向支持
messense/dav-server-rs pull request #11
Opened 2022-08-14 14:51 UTC by sihuan

对于一些非典型的后端，比如阿里云盘，在 GET 时可以通过 302 重定向到文件直链，从而使 WebDAV 客户端直接从阿里云盘服务器读取文件。

2022-08-14 14:56 UTC, messense commented on src/davhandler.rs
> +    pub(crate) redirect: Option<bool>
没必要 Option，可以直接 bool 默认值就是 false.

2022-08-14 14:57 UTC, sihuan commented on src/davhandler.rs
> +    pub(crate) redirect: Option<bool>
刚刚学 rust 😆，几乎是边查文档边写的，看到上面 autoindex 用了 Option 就抄下来了

2022-08-14 15:00 UTC, messense commented on src/davhandler.rs
> +    pub(crate) redirect: Option<bool>
也行，先保持一致吧

2022-08-14 15:00 UTC, messense commented
需要跑一下 `cargo fmt`

2022-08-14 15:03 UTC, messense commented on src/davhandler.rs
> +    // Dose GET on a file return 302 redirect.
```suggestion
    // Does GET on a file return 302 redirect.
```

2022-08-14 15:18 UTC, messense commented on src/fs.rs
> +    fn redirect_url(&mut self) -> FsFuture<String> {
返回 string 再 parse 成 url 还需要处理错误，不如直接要求返回 [`Url`](https://docs.rs/url/2.2.2/url/struct.Url.html)

```suggestion
    fn redirect_url(&mut self) -> FsFuture<Url> {
```

2022-08-15 02:04 UTC, messense requested changes

2022-08-15 02:04 UTC, messense commented on src/fs.rs
> +    fn redirect_url(&mut self) -> FsFuture<Url> {
这里我看错了，可以返回 string，`src/handle_gethead.rs` L102 的 `parse().unwrap()` 需要的应该是一个 `HeaderValue`

2022-08-15 02:04 UTC, messense commented on src/fs.rs
> +    fn redirect_url(&mut self) -> FsFuture<Url> {
```suggestion
    fn redirect_url(&mut self) -> FsFuture<Option<String>> {
```
改成返回 `Option<String>` 吧，这样可以默认返回 `None`，在 handle_gethead 中对 `None` 的情况就继续往下走。

2022-08-15 02:06 UTC, messense commented on src/fs.rs
> +        notimplemented_fut!("redirect_url")
```suggestion
        future::ready(None)
```

2022-08-15 02:32 UTC, messense approved these changes
LGTM, thanks!

2022-08-15 02:32 UTC, merged

2022-08-15 02:36 UTC, messense commented
Released in v0.5.0.